# Bank Marketing Campaign Analysis

## 1. Data Preprocessing

### Objective
Load the Bank Marketing dataset, understand its structure,
identify data quality issues, and prepare it for exploratory
data analysis.

In [32]:
import pandas as pd

In [33]:
df=pd.read_csv('../data/bank-full.csv',sep=';')

In [34]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [35]:
print("Dataset Shape: ",df.shape)

Dataset Shape:  (45211, 17)

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  str
 2   marital    45211 non-null  str
 3   education  45211 non-null  str
 4   default    45211 non-null  str
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  str
 7   loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   day        45211 non-null  int64
 10  month      45211 non-null  str
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  y          45211 non-null  str
dtypes: int64(7), str(10)
memory usage: 8.1 MB

In [37]:
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

In [38]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
cat_cols = df.select_dtypes(include="object").columns

for col in cat_cols:
    print(f"\nColumn: {col}")
    print(df[col].unique())

Column: job
<ArrowStringArray>
[   'management',    'technician',  'entrepreneur',   'blue-collar',
       'unknown',       'retired',        'admin.',      'services',
 'self-employed',    'unemployed',     'housemaid',       'student']
Length: 12, dtype: str

Column: marital
<ArrowStringArray>
['married', 'single', 'divorced']
Length: 3, dtype: str

Column: education
<ArrowStringArray>
['tertiary', 'secondary', 'unknown', 'primary']
Length: 4, dtype: str

Column: default
<ArrowStringArray>
['no', 'yes']
Length: 2, dtype: str

Column: housing
<ArrowStringArray>
['yes', 'no']
Length: 2, dtype: str

Column: loan
<ArrowStringArray>
['no', 'yes']
Length: 2, dtype: str

Column: contact
<ArrowStringArray>
['unknown', 'cellular', 'telephone']
Length: 3, dtype: str

Column: month
<ArrowStringArray>
['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb', 'mar', 'apr',
 'sep']
Length: 12, dtype: str

Column: poutcome
<ArrowStringArray>
['unknown', 'failure', 'other', 'success']
Length: 4, dtype: str

Column: y
<ArrowStringArray>
['no', 'yes']
Length: 2, dtype: str

C:\Users\barad\AppData\Local\Temp\ipykernel_28916\3554788404.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include="object").columns

In [41]:
for col in cat_cols:
    unknown_count=(df[col]=='unknown').sum()

    if unknown_count>0:
        print(f"{col}: {unknown_count}")

job: 288
education: 1857
contact: 13020
poutcome: 36959

In [42]:
df['y'].value_counts()

y
no     39922
yes     5289
Name: count, dtype: int64

In [43]:
df["y"].value_counts(normalize=True) * 100

y
no     88.30152
yes    11.69848
Name: proportion, dtype: float64

In [44]:
print("Dataset shape:", df.shape)
print("Duplicates remaining:", df.duplicated().sum())

Dataset shape: (45211, 17)
Duplicates remaining: 0